name: API CI
# on: [push] // asi se hace on cuando solo manejamos un proyecto simple, pero como manejamos un monorepo debemos hacer mas especifico la config
on:  
  push:
    paths:
      - "./api/**"
      - ".github/workflows/api-ci.yml"

jobs:
  unit-test:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: ./api

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ./api/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: run unit test 
        run: npm run lint


  linter:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: ./api

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ./api/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: run unit test 
        run: npm run test

      